version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./webapp_content/:/webapp/
    depends_on:
     - php
  php:
    build: ./docker/php
    volumes:
      - ./webapp_engine/:/webapp/
