LANGS
  pol Polski
  eng English

TITLE_LOGIN
  Logowanie do serwisu
  Login to website

TITLE_REGISTER
  Rejestracja użytkownika
  User registration

TITLE_SETTINGS
  Ustawienia użytkownika
  User settings

TITLE_BROWSE
  Przeglądanie notatek
  Browsing notes

TITLE_EDIT
  Edycja notatki
  Note editing

ERROR_LOGIN_MAIL
  Użytkownik "{}" nie istnieje!
  User "{}" not found!

ERROR_LOGIN_PASS
  Niewłaściwe hasło dla "{}".
  Incorrect password for "{}".

ERROR_REGISTER_HUMAN
  Nie jesteś człowiekiem. Odejdź.
  You are not a human. Go away.

ERROR_REGISTER_EMAIL
  Proszę podać adres e-mail!
  Please provide an e-mail address!

ERROR_REGISTER_PASS
  Proszę podać hasło!
  Please provide a password!

ERROR_REGISTER_PASSMISS
  Hasła nie pasują do siebie! Spróbuj ponownie.
  Password mismatch! Try again.

ERROR_REGISTER_EXISTS
  Przepraszamy, użytkownik "{}" już istnieje.
  Sorry, user "{}" already exists.

ERROR_REGISTER_ANYTHING
  Przepraszamy, nie udało się dodać użytkownika do bazy!
  Sorry, could not add user to the database!

SUCCESS_REGISTER
  Pomyślnie zarejestrowano konto! :)
  Successfully registered account! :)

SESSION_REQUIRED
  Musisz być zalogowany, aby mieć dostęp do tej strony.
  You must be logged in in order to acces this site.

SESSION_EXPIRED
  Sesja wygasła. Zaloguj się ponownie.
  Session has expired. Log in again.

SUCCESS_LOGOFF
  Wylogowano pomyślnie.
  Logged off successfully.


